#ifndef FF_CONFIG_H
#define FF_CONFIG_H

#ifndef ICONV_CONST
#define ICONV_CONST
#endif

#define _NO_LIBUNINAMESLIST 1
#define _NO_LIBUNICODENAMES 1
#define _NO_PYTHON
#define _NO_FFSCRIPT
#define _NO_LIBSPIRO

#define FONTFORGE_LIBFF_VERSION_MAJOR 2
#define FONTFORGE_LIBFF_VERSION_MINOR 0
#define FONTFORGE_MODTIME_RAW 1469132312L /* Seconds since 1970 (standard unix time) */
#define FONTFORGE_MODTIME_STR ""
#define FONTFORGE_VERSIONDATE_RAW 20160721

#define _GNU_SOURCE 1

#endif
