#!/bin/zsh

# stibizt: https://cmake.org/Bug/view.php?id=15507

code_sign_identity="Developer ID"

if [ -z $1 ]; then
    echo "Usage: codesign_miktex /path/MiKTeX\ Console.app"
    exit 1
fi

app_dir=$1

find "$app_dir"/Contents/Frameworks -type f -exec codesign --force --verbose --sign "$code_sign_identity" {} \;
find "$app_dir"/Contents/bin -type f -exec codesign --force --verbose --sign "$code_sign_identity" {} \;
find "$app_dir"/Contents/libexec -type f -exec codesign --force --verbose --sign "$code_sign_identity" {} \;
find "$app_dir"/Contents/MacOS -type f -exec codesign --force --verbose --sign "$code_sign_identity" {} \;

find "$app_dir"/Contents/PlugIns -name "*.dylib" -exec codesign --force --verbose --sign "$code_sign_identity" {} \;

codesign --force --verbose --sign "$code_sign_identity" "$app_dir"

echo "Verifying..."
spctl -a -t exec -vv "$app_dir"
