/***** Autogenerated from runfile.in; changes will be overwritten *****/

#ifndef runfile_H
#define runfile_H
namespace run {
void nullFile(vm::stack *);
void namePart(vm::stack *);
void modePart(vm::stack *);
void dimensionSetHelper(vm::stack *);
void dimensionSet(vm::stack *);
void dimensionPart(vm::stack *);
void lineSetHelper(vm::stack *);
void lineSet(vm::stack *);
void linePart(vm::stack *);
void csvSetHelper(vm::stack *);
void csvSet(vm::stack *);
void csvPart(vm::stack *);
void wordSetHelper(vm::stack *);
void wordSet(vm::stack *);
void wordPart(vm::stack *);
void singlerealSetHelper(vm::stack *);
void singlerealSet(vm::stack *);
void singlerealPart(vm::stack *);
void singleintSetHelper(vm::stack *);
void singleintSet(vm::stack *);
void singleintPart(vm::stack *);
void signedintSetHelper(vm::stack *);
void signedintSet(vm::stack *);
void signedintPart(vm::stack *);
void readSetHelper(vm::stack *);
void readSet(vm::stack *);
}

#endif // runfile_H
