/***** Autogenerated from runmath.in; changes will be overwritten *****/

#pragma once
namespace run {
void boolMemEq(vm::stack *);
void boolMemNeq(vm::stack *);
void boolFuncEq(vm::stack *);
void boolFuncNeq(vm::stack *);
}

