/***** Autogenerated from runpair.in; changes will be overwritten *****/

#ifndef runpair_H
#define runpair_H
namespace run {
void pairZero(vm::stack *);
void realRealToPair(vm::stack *);
void pairNegate(vm::stack *);
void pairXPart(vm::stack *);
void pairYPart(vm::stack *);
}

#endif // runpair_H
