/*****
 * This file is automatically generated by findsym.pl
 * Changes will be overwritten.
 *****/

// If the ADDSYMBOL macro is not already defined, define it with the default
// purpose of referring to an external pre-translated symbol, such that
// SYM(name) also refers to that symbol.
#ifndef ADDSYMBOL
    #define ADDSYMBOL(name) extern sym::symbol PRETRANSLATED_SYMBOL_##name
    #define SYM(name) PRETRANSLATED_SYMBOL_##name
#endif

ADDSYMBOL(a);
ADDSYMBOL(accel);
ADDSYMBOL(arclength);
ADDSYMBOL(arctime);
ADDSYMBOL(b);
ADDSYMBOL(c);
ADDSYMBOL(c0);
ADDSYMBOL(c1);
ADDSYMBOL(cyclic);
ADDSYMBOL(d);
ADDSYMBOL(dir);
ADDSYMBOL(dval);
ADDSYMBOL(e);
ADDSYMBOL(fuzz);
ADDSYMBOL(g);
ADDSYMBOL(insphere);
ADDSYMBOL(intersect);
ADDSYMBOL(intersections);
ADDSYMBOL(length);
ADDSYMBOL(max);
ADDSYMBOL(maxratio);
ADDSYMBOL(maxtimes);
ADDSYMBOL(min);
ADDSYMBOL(minratio);
ADDSYMBOL(mintimes);
ADDSYMBOL(normalize);
ADDSYMBOL(orient);
ADDSYMBOL(p);
ADDSYMBOL(path3);
ADDSYMBOL(piecewisestraight);
ADDSYMBOL(point);
ADDSYMBOL(post);
ADDSYMBOL(postcontrol);
ADDSYMBOL(pre);
ADDSYMBOL(precontrol);
ADDSYMBOL(q);
ADDSYMBOL(radius);
ADDSYMBOL(reverse);
ADDSYMBOL(sign);
ADDSYMBOL(size);
ADDSYMBOL(straight);
ADDSYMBOL(straightness);
ADDSYMBOL(subpath);
ADDSYMBOL(t);
ADDSYMBOL(unstraighten);
ADDSYMBOL(z0);
ADDSYMBOL(z1);
