/***** Autogenerated from runpair.in; changes will be overwritten *****/

#pragma once
namespace run {
void pairZero(vm::stack *);
void realRealToPair(vm::stack *);
void pairNegate(vm::stack *);
void pairXPart(vm::stack *);
void pairYPart(vm::stack *);
}

