/***** Autogenerated from runtriple.in; changes will be overwritten *****/

#pragma once
namespace run {
void tripleZero(vm::stack *);
void realRealRealToTriple(vm::stack *);
void tripleXPart(vm::stack *);
void tripleYPart(vm::stack *);
void tripleZPart(vm::stack *);
}

