/***** Autogenerated from runtriple.in; changes will be overwritten *****/

#ifndef runtriple_H
#define runtriple_H
namespace run {
void tripleZero(vm::stack *);
void realRealRealToTriple(vm::stack *);
void tripleXPart(vm::stack *);
void tripleYPart(vm::stack *);
void tripleZPart(vm::stack *);
}

#endif // runtriple_H
