/*****
 * This file is automatically generated by findsym.pl
 * Changes will be overwritten.
 *****/

// If the ADDSYMBOL macro is not already defined, define it with the default
// purpose of referring to an external pre-translated symbol, such that
// SYM(name) also refers to that symbol.
#ifndef ADDSYMBOL
    #define ADDSYMBOL(name) extern sym::symbol PRETRANSLATED_SYMBOL_##name
    #define SYM(name) PRETRANSLATED_SYMBOL_##name
#endif

ADDSYMBOL(a);
ADDSYMBOL(abs);
ADDSYMBOL(abs2);
ADDSYMBOL(azimuth);
ADDSYMBOL(b);
ADDSYMBOL(bezier);
ADDSYMBOL(bezierP);
ADDSYMBOL(bezierPP);
ADDSYMBOL(bezierPPP);
ADDSYMBOL(c);
ADDSYMBOL(colatitude);
ADDSYMBOL(cross);
ADDSYMBOL(d);
ADDSYMBOL(dir);
ADDSYMBOL(dot);
ADDSYMBOL(expi);
ADDSYMBOL(latitude);
ADDSYMBOL(length);
ADDSYMBOL(longitude);
ADDSYMBOL(perp);
ADDSYMBOL(polar);
ADDSYMBOL(realmult);
ADDSYMBOL(t);
ADDSYMBOL(u);
ADDSYMBOL(unit);
ADDSYMBOL(v);
ADDSYMBOL(warn);
ADDSYMBOL(x);
ADDSYMBOL(xpart);
ADDSYMBOL(ypart);
ADDSYMBOL(z);
ADDSYMBOL(zpart);
