[${MIKTEX_CONFIG_SECTION_CORE_FILETYPES}.tex]

	!clear ${MIKTEX_CONFIG_VALUE_PATHS}
	${MIKTEX_CONFIG_VALUE_PATHS} = .
	${MIKTEX_CONFIG_VALUE_PATHS} = %R/tex/harflatex//
	${MIKTEX_CONFIG_VALUE_PATHS} = %R/tex/harftex//
	${MIKTEX_CONFIG_VALUE_PATHS} = %R/tex/lualatex//
	${MIKTEX_CONFIG_VALUE_PATHS} = %R/tex/latex//
	${MIKTEX_CONFIG_VALUE_PATHS} = %R/tex/luatex//
	${MIKTEX_CONFIG_VALUE_PATHS} = %R/tex/generic//
	${MIKTEX_CONFIG_VALUE_PATHS} = %R/tex//

	!clear ${MIKTEX_CONFIG_VALUE_ALTEXTENSIONS}
	${MIKTEX_CONFIG_VALUE_ALTEXTENSIONS} = .sty
	${MIKTEX_CONFIG_VALUE_ALTEXTENSIONS} = .cls
	${MIKTEX_CONFIG_VALUE_ALTEXTENSIONS} = .fd
	${MIKTEX_CONFIG_VALUE_ALTEXTENSIONS} = .aux
	${MIKTEX_CONFIG_VALUE_ALTEXTENSIONS} = .bbl
	${MIKTEX_CONFIG_VALUE_ALTEXTENSIONS} = .def
	${MIKTEX_CONFIG_VALUE_ALTEXTENSIONS} = .clo
	${MIKTEX_CONFIG_VALUE_ALTEXTENSIONS} = .ldf
