[Paths]
  CommonInstall=${MIKTEX_SANDBOX_BINARY_DIR}
  CommonConfig=${MIKTEX_SANDBOX_BINARY_DIR}
  CommonData=${MIKTEX_SANDBOX_BINARY_DIR}
  UserInstall=${MIKTEX_SANDBOX_BINARY_DIR}
  UserConfig=${MIKTEX_SANDBOX_BINARY_DIR}
  UserData=${MIKTEX_SANDBOX_BINARY_DIR}
