## features.cmake					-*- CMake -*-
##
## Copyright (C) 2013-2016 Christian Schenk
## 
## This file is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published
## by the Free Software Foundation; either version 2, or (at your
## option) any later version.
## 
## This file is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this file; if not, write to the Free Software
## Foundation, 59 Temple Place - Suite 330, Boston, MA 02111-1307,
## USA.

include(sources.cmake)

set(supported_cairo_headers ${cairo_headers})
#set unsupported_cairo_headers =
set(all_cairo_headers ${cairo_headers})
set(all_cairo_private ${cairo_private})
set(all_cairo_cxx_sources ${cairo_cxx_sources})
set(all_cairo_sources ${cairo_sources})

set(enabled_cairo_headers ${cairo_headers})
set(enabled_cairo_private ${cairo_private})
set(enabled_cairo_cxx_sources ${cairo_cxx_sources})
set(enabled_cairo_sources ${cairo_sources})

set(all_cairo_pkgconf cairo.pc)
set(enabled_cairo_pkgconf cairo.pc)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_xlib_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_xlib_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_xlib_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_xlib_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_xlib_sources})
if(CAIRO_HAS_XLIB_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_xlib_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_xlib_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_xlib_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_xlib_sources})
endif(CAIRO_HAS_XLIB_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-xlib.pc)
if(CAIRO_HAS_XLIB_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-xlib.pc)
endif(CAIRO_HAS_XLIB_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_xlib_xrender_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_xlib_xrender_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_xlib_xrender_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_xlib_xrender_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_xlib_xrender_sources})
if(CAIRO_HAS_XLIB_XRENDER_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_xlib_xrender_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_xlib_xrender_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_xlib_xrender_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_xlib_xrender_sources})
endif(CAIRO_HAS_XLIB_XRENDER_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-xlib-xrender.pc)
if(CAIRO_HAS_XLIB_XRENDER_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-xlib-xrender.pc)
endif(CAIRO_HAS_XLIB_XRENDER_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_xcb_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_xcb_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_xcb_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_xcb_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_xcb_sources})
if(CAIRO_HAS_XCB_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_xcb_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_xcb_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_xcb_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_xcb_sources})
endif(CAIRO_HAS_XCB_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-xcb.pc)
if(CAIRO_HAS_XCB_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-xcb.pc)
endif(CAIRO_HAS_XCB_SURFACE)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_xlib_xcb_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_xlib_xcb_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_xlib_xcb_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_xlib_xcb_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_xlib_xcb_sources})
if(CAIRO_HAS_XLIB_XCB_FUNCTIONS)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_xlib_xcb_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_xlib_xcb_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_xlib_xcb_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_xlib_xcb_sources})
endif(CAIRO_HAS_XLIB_XCB_FUNCTIONS)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-xlib-xcb.pc)
if(CAIRO_HAS_XLIB_XCB_FUNCTIONS)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-xlib-xcb.pc)
endif(CAIRO_HAS_XLIB_XCB_FUNCTIONS)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_xcb_shm_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_xcb_shm_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_xcb_shm_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_xcb_shm_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_xcb_shm_sources})
if(CAIRO_HAS_XCB_SHM_FUNCTIONS)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_xcb_shm_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_xcb_shm_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_xcb_shm_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_xcb_shm_sources})
endif(CAIRO_HAS_XCB_SHM_FUNCTIONS)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-xcb-shm.pc)
if(CAIRO_HAS_XCB_SHM_FUNCTIONS)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-xcb-shm.pc)
endif(CAIRO_HAS_XCB_SHM_FUNCTIONS)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_qt_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_qt_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_qt_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_qt_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_qt_sources})
if(CAIRO_HAS_QT_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_qt_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_qt_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_qt_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_qt_sources})
endif(CAIRO_HAS_QT_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-qt.pc)
if(CAIRO_HAS_QT_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-qt.pc)
endif(CAIRO_HAS_QT_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_quartz_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_quartz_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_quartz_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_quartz_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_quartz_sources})
if(CAIRO_HAS_QUARTZ_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_quartz_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_quartz_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_quartz_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_quartz_sources})
endif(CAIRO_HAS_QUARTZ_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-quartz.pc)
if(CAIRO_HAS_QUARTZ_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-quartz.pc)
endif(CAIRO_HAS_QUARTZ_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_quartz_font_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_quartz_font_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_quartz_font_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_quartz_font_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_quartz_font_sources})
if(CAIRO_HAS_QUARTZ_FONT)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_quartz_font_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_quartz_font_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_quartz_font_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_quartz_font_sources})
endif(CAIRO_HAS_QUARTZ_FONT)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-quartz-font.pc)
if(CAIRO_HAS_QUARTZ_FONT)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-quartz-font.pc)
endif(CAIRO_HAS_QUARTZ_FONT)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_quartz_image_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_quartz_image_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_quartz_image_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_quartz_image_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_quartz_image_sources})
if(CAIRO_HAS_QUARTZ_IMAGE_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_quartz_image_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_quartz_image_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_quartz_image_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_quartz_image_sources})
endif(CAIRO_HAS_QUARTZ_IMAGE_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-quartz-image.pc)
if(CAIRO_HAS_QUARTZ_IMAGE_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-quartz-image.pc)
endif(CAIRO_HAS_QUARTZ_IMAGE_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_win32_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_win32_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_win32_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_win32_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_win32_sources})
if(CAIRO_HAS_WIN32_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_win32_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_win32_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_win32_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_win32_sources})
endif(CAIRO_HAS_WIN32_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-win32.pc)
if(CAIRO_HAS_WIN32_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-win32.pc)
endif(CAIRO_HAS_WIN32_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_win32_font_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_win32_font_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_win32_font_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_win32_font_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_win32_font_sources})
if(CAIRO_HAS_WIN32_FONT)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_win32_font_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_win32_font_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_win32_font_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_win32_font_sources})
endif(CAIRO_HAS_WIN32_FONT)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-win32-font.pc)
if(CAIRO_HAS_WIN32_FONT)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-win32-font.pc)
endif(CAIRO_HAS_WIN32_FONT)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_skia_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_skia_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_skia_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_skia_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_skia_sources})
if(CAIRO_HAS_SKIA_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_skia_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_skia_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_skia_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_skia_sources})
endif(CAIRO_HAS_SKIA_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-skia.pc)
if(CAIRO_HAS_SKIA_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-skia.pc)
endif(CAIRO_HAS_SKIA_SURFACE)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_os2_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_os2_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_os2_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_os2_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_os2_sources})
if(CAIRO_HAS_OS2_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_os2_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_os2_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_os2_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_os2_sources})
endif(CAIRO_HAS_OS2_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-os2.pc)
if(CAIRO_HAS_OS2_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-os2.pc)
endif(CAIRO_HAS_OS2_SURFACE)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_beos_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_beos_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_beos_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_beos_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_beos_sources})
if(CAIRO_HAS_BEOS_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_beos_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_beos_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_beos_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_beos_sources})
endif(CAIRO_HAS_BEOS_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-beos.pc)
if(CAIRO_HAS_BEOS_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-beos.pc)
endif(CAIRO_HAS_BEOS_SURFACE)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_drm_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_drm_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_drm_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_drm_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_drm_sources})
if(CAIRO_HAS_DRM_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_drm_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_drm_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_drm_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_drm_sources})
endif(CAIRO_HAS_DRM_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-drm.pc)
if(CAIRO_HAS_DRM_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-drm.pc)
endif(CAIRO_HAS_DRM_SURFACE)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_gallium_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_gallium_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_gallium_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_gallium_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_gallium_sources})
if(CAIRO_HAS_GALLIUM_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_gallium_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_gallium_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_gallium_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_gallium_sources})
endif(CAIRO_HAS_GALLIUM_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-gallium.pc)
if(CAIRO_HAS_GALLIUM_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-gallium.pc)
endif(CAIRO_HAS_GALLIUM_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_png_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_png_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_png_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_png_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_png_sources})
if(CAIRO_HAS_PNG_FUNCTIONS)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_png_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_png_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_png_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_png_sources})
endif(CAIRO_HAS_PNG_FUNCTIONS)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-png.pc)
if(CAIRO_HAS_PNG_FUNCTIONS)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-png.pc)
endif(CAIRO_HAS_PNG_FUNCTIONS)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_gl_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_gl_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_gl_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_gl_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_gl_sources})
if(CAIRO_HAS_GL_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_gl_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_gl_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_gl_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_gl_sources})
endif(CAIRO_HAS_GL_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-gl.pc)
if(CAIRO_HAS_GL_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-gl.pc)
endif(CAIRO_HAS_GL_SURFACE)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_glesv2_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_glesv2_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_glesv2_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_glesv2_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_glesv2_sources})
if(CAIRO_HAS_GLESV2_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_glesv2_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_glesv2_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_glesv2_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_glesv2_sources})
endif(CAIRO_HAS_GLESV2_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-glesv2.pc)
if(CAIRO_HAS_GLESV2_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-glesv2.pc)
endif(CAIRO_HAS_GLESV2_SURFACE)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_cogl_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_cogl_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_cogl_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_cogl_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_cogl_sources})
if(CAIRO_HAS_COGL_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_cogl_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_cogl_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_cogl_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_cogl_sources})
endif(CAIRO_HAS_COGL_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-cogl.pc)
if(CAIRO_HAS_COGL_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-cogl.pc)
endif(CAIRO_HAS_COGL_SURFACE)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_directfb_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_directfb_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_directfb_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_directfb_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_directfb_sources})
if(CAIRO_HAS_DIRECTFB_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_directfb_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_directfb_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_directfb_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_directfb_sources})
endif(CAIRO_HAS_DIRECTFB_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-directfb.pc)
if(CAIRO_HAS_DIRECTFB_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-directfb.pc)
endif(CAIRO_HAS_DIRECTFB_SURFACE)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_vg_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_vg_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_vg_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_vg_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_vg_sources})
if(CAIRO_HAS_VG_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_vg_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_vg_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_vg_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_vg_sources})
endif(CAIRO_HAS_VG_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-vg.pc)
if(CAIRO_HAS_VG_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-vg.pc)
endif(CAIRO_HAS_VG_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_egl_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_egl_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_egl_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_egl_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_egl_sources})
if(CAIRO_HAS_EGL_FUNCTIONS)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_egl_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_egl_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_egl_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_egl_sources})
endif(CAIRO_HAS_EGL_FUNCTIONS)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-egl.pc)
if(CAIRO_HAS_EGL_FUNCTIONS)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-egl.pc)
endif(CAIRO_HAS_EGL_FUNCTIONS)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_glx_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_glx_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_glx_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_glx_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_glx_sources})
if(CAIRO_HAS_GLX_FUNCTIONS)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_glx_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_glx_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_glx_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_glx_sources})
endif(CAIRO_HAS_GLX_FUNCTIONS)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-glx.pc)
if(CAIRO_HAS_GLX_FUNCTIONS)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-glx.pc)
endif(CAIRO_HAS_GLX_FUNCTIONS)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_wgl_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_wgl_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_wgl_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_wgl_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_wgl_sources})
if(CAIRO_HAS_WGL_FUNCTIONS)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_wgl_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_wgl_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_wgl_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_wgl_sources})
endif(CAIRO_HAS_WGL_FUNCTIONS)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-wgl.pc)
if(CAIRO_HAS_WGL_FUNCTIONS)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-wgl.pc)
endif(CAIRO_HAS_WGL_FUNCTIONS)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_script_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_script_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_script_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_script_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_script_sources})
if(CAIRO_HAS_SCRIPT_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_script_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_script_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_script_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_script_sources})
endif(CAIRO_HAS_SCRIPT_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-script.pc)
if(CAIRO_HAS_SCRIPT_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-script.pc)
endif(CAIRO_HAS_SCRIPT_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_ft_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_ft_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_ft_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_ft_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_ft_sources})
if(CAIRO_HAS_FT_FONT)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_ft_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_ft_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_ft_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_ft_sources})
endif(CAIRO_HAS_FT_FONT)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-ft.pc)
if(CAIRO_HAS_FT_FONT)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-ft.pc)
endif(CAIRO_HAS_FT_FONT)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_fc_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_fc_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_fc_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_fc_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_fc_sources})
if(CAIRO_HAS_FC_FONT)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_fc_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_fc_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_fc_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_fc_sources})
endif(CAIRO_HAS_FC_FONT)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-fc.pc)
if(CAIRO_HAS_FC_FONT)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-fc.pc)
endif(CAIRO_HAS_FC_FONT)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_ps_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_ps_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_ps_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_ps_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_ps_sources})
if(CAIRO_HAS_PS_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_ps_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_ps_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_ps_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_ps_sources})
endif(CAIRO_HAS_PS_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-ps.pc)
if(CAIRO_HAS_PS_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-ps.pc)
endif(CAIRO_HAS_PS_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_pdf_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_pdf_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_pdf_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_pdf_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_pdf_sources})
if(CAIRO_HAS_PDF_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_pdf_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_pdf_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_pdf_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_pdf_sources})
endif(CAIRO_HAS_PDF_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-pdf.pc)
if(CAIRO_HAS_PDF_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-pdf.pc)
endif(CAIRO_HAS_PDF_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_svg_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_svg_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_svg_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_svg_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_svg_sources})
if(CAIRO_HAS_SVG_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_svg_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_svg_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_svg_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_svg_sources})
endif(CAIRO_HAS_SVG_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-svg.pc)
if(CAIRO_HAS_SVG_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-svg.pc)
endif(CAIRO_HAS_SVG_SURFACE)

set(all_cairo_private ${all_cairo_private} ${cairo_test_surfaces_private} ${cairo_test_surfaces_headers})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_test_surfaces_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_test_surfaces_sources})
if(CAIRO_HAS_TEST_SURFACES)
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_test_surfaces_private} ${cairo_test_surfaces_headers})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_test_surfaces_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_test_surfaces_sources})
endif(CAIRO_HAS_TEST_SURFACES)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_image_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_image_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_image_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_image_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_image_sources})
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_image_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_image_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_image_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_image_sources})

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_mime_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_mime_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_mime_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_mime_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_mime_sources})
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_mime_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_mime_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_mime_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_mime_sources})

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_recording_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_recording_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_recording_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_recording_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_recording_sources})
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_recording_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_recording_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_recording_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_recording_sources})

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_observer_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_observer_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_observer_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_observer_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_observer_sources})
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_observer_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_observer_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_observer_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_observer_sources})

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_tee_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_tee_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_tee_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_tee_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_tee_sources})
if(CAIRO_HAS_TEE_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_tee_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_tee_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_tee_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_tee_sources})
endif(CAIRO_HAS_TEE_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-tee.pc)
if(CAIRO_HAS_TEE_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-tee.pc)
endif(CAIRO_HAS_TEE_SURFACE)

set(unsupported_cairo_headers ${unsupported_cairo_headers} ${cairo_xml_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_xml_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_xml_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_xml_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_xml_sources})
if(CAIRO_HAS_XML_SURFACE)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_xml_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_xml_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_xml_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_xml_sources})
endif(CAIRO_HAS_XML_SURFACE)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-xml.pc)
if(CAIRO_HAS_XML_SURFACE)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-xml.pc)
endif(CAIRO_HAS_XML_SURFACE)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_user_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_user_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_user_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_user_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_user_sources})
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_user_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_user_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_user_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_user_sources})

set(all_cairo_private ${all_cairo_private} ${cairo_pthread_private} ${cairo_pthread_headers})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_pthread_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_pthread_sources})
if(CAIRO_HAS_PTHREAD)
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_pthread_private} ${cairo_pthread_headers})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_pthread_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_pthread_sources})
endif(CAIRO_HAS_PTHREAD)

set(supported_cairo_headers ${supported_cairo_headers} ${cairo_gobject_headers})
set(all_cairo_headers ${all_cairo_headers} ${cairo_gobject_headers})
set(all_cairo_private ${all_cairo_private} ${cairo_gobject_private})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_gobject_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_gobject_sources})
if(CAIRO_HAS_GOBJECT_FUNCTIONS)
set(enabled_cairo_headers ${enabled_cairo_headers} ${cairo_gobject_headers})
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_gobject_private})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_gobject_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_gobject_sources})
endif(CAIRO_HAS_GOBJECT_FUNCTIONS)
set(all_cairo_pkgconf ${all_cairo_pkgconf} cairo-gobject.pc)
if(CAIRO_HAS_GOBJECT_FUNCTIONS)
set(enabled_cairo_pkgconf ${enabled_cairo_pkgconf} cairo-gobject.pc)
endif(CAIRO_HAS_GOBJECT_FUNCTIONS)

set(all_cairo_private ${all_cairo_private} ${cairo_trace_private} ${cairo_trace_headers})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_trace_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_trace_sources})
if(CAIRO_HAS_TRACE)
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_trace_private} ${cairo_trace_headers})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_trace_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_trace_sources})
endif(CAIRO_HAS_TRACE)

set(all_cairo_private ${all_cairo_private} ${cairo_interpreter_private} ${cairo_interpreter_headers})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_interpreter_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_interpreter_sources})
if(CAIRO_HAS_INTERPRETER)
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_interpreter_private} ${cairo_interpreter_headers})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_interpreter_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_interpreter_sources})
endif(CAIRO_HAS_INTERPRETER)

set(all_cairo_private ${all_cairo_private} ${cairo_symbol_lookup_private} ${cairo_symbol_lookup_headers})
set(all_cairo_cxx_sources ${all_cairo_cxx_sources} ${cairo_symbol_lookup_cxx_sources})
set(all_cairo_sources ${all_cairo_sources} ${cairo_symbol_lookup_sources})
if(CAIRO_HAS_SYMBOL_LOOKUP)
set(enabled_cairo_private ${enabled_cairo_private} ${cairo_symbol_lookup_private} ${cairo_symbol_lookup_headers})
set(enabled_cairo_cxx_sources ${enabled_cairo_cxx_sources} ${cairo_symbol_lookup_cxx_sources})
set(enabled_cairo_sources ${enabled_cairo_sources} ${cairo_symbol_lookup_sources})
endif(CAIRO_HAS_SYMBOL_LOOKUP)
