//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by yap.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDD_ADVANCED_OPTIONS            101
#define IDD_DISPLAY                     102
#define IDD_DVIPS                       103
#define IDD_GOTOPAGE                    104
#define IDD_INVERSE_SEARCH              105
#define IDD_MAGNIFYING_GLASS            106
#define IDD_PRINTER                     107
#define IDD_PROGRESS_INDICATOR          108
#define IDD_SECURITY                    109
#define IDD_SOURCE_SPECIALS             110
#define IDD_USER_INTERFACE              111
#define IDD_DOC_PROP_GENERAL            112
#define IDD_DOC_PROP_FONTS              113
#define IDD_ADD_EDITOR                  114
#define IDP_FILE_ASSOCIATION            115
#define IDS_PS_DISABLED                 116
#define IDP_CHOOSE_EDITOR               117
#define IDR_MAINFRAME                   128
#define IDR_CONTEXT_MENU                129
#define IDR_DVITYPE                     130
#define IDR_FULLSCREEN                  131
#define IDR_POINT_MENU                  132
#define IDD_SPLASH                      133
#define IDB_SPLASH                      134
#define IDC_CHECK_ASSOCIATION           1000
#define IDC_CLOSE                       1001
#define IDC_COMBO_DISPLAY_MODE          1002
#define IDC_COMBO_DISPLAY_SHRINK_FACTOR 1003
#define IDC_LISTBOX_EDITOR              1004
#define IDC_COMBO_PAGENO                1005
#define IDC_COMBO_PRINTER_MODE          1006
#define IDC_ALL_PAGES                   1007
#define IDC_CURRENT_PAGE                1008
#define IDC_PAGE_RANGE                  1009
#define IDC_EVEN_ODD_PAGES              1010
#define IDC_EVEN_PAGES                  1011
#define IDC_FIRST_PAGE                  1012
#define IDC_LAST_PAGE                   1013
#define IDC_ODD_PAGES                   1014
#define IDC_EDIT2                       1015
#define IDC_EDIT3                       1017
#define IDC_ARGUMENTS                   1018
#define IDC_EDIT_SOURCE                 1019
#define IDC_GOTO                        1020
#define IDC_HAND_POINT                  1021
#define IDC_HAND_TOOL                   1022
#define IDC_HIDE_CURSOR                 1023
#define IDC_MAG                         1024
#define IDC_MAGGLASS_LARGE_HEIGHT       1025
#define IDC_MAGGLASS_LARGE_SHRINK_FACTOR 1026
#define IDC_MAGGLASS_LARGE_WIDTH        1027
#define IDC_MAGGLASS_MEDIUM_HEIGHT      1028
#define IDC_MAGGLASS_MEDIUM_SHRINK_FACTOR 1029
#define IDC_MAGGLASS_MEDIUM_WIDTH       1030
#define IDC_MAGGLASS_SMALL_HEIGHT       1031
#define IDC_MAGGLASS_SMALL_SHRINK_FACTOR 1032
#define IDC_MAGGLASS_SMALL_WIDTH        1033
#define IDC_MAINTAIN_HORZ_POS           1034
#define IDC_MAINTAIN_VERT_POS           1035
#define IDC_PRESSED_HAND                1036
#define IDC_PROGRESS1                   1037
#define IDC_SECURITY_ASK_USER           1038
#define IDC_SECURITY_DISABLE_COMMANDS   1039
#define IDC_SECURITY_EDIT_SECURE_COMMANDS 1040
#define IDC_SECURITY_ENABLE_ALL_COMMANDS 1041
#define IDC_SECURITY_SECURE_COMMANDS    1042
#define IDC_SHOW_SOURCE_SPECIALS        1043
#define IDC_SOURCE_SPECIALS             1044
#define IDC_STATIC_RESOLUTION           1045
#define IDC_COMBO_PRINTER_NAME          1046
#define IDC_EDIT_FILE                   1047
#define IDC_EDIT_COMMENT                1048
#define IDC_LIST                        1049
#define IDC_EDIT_CREATED                1050
#define IDC_THE_NAME_OF_THE_GAME        1051
#define IDC_EDIT_MODIFIED               1052
#define IDC_PATH                        1053
#define IDC_COMMAND_LINE                1054
#define IDC_EDIT_SIZE                   1055
#define IDC_BROWSE                      1056
#define IDC_EDIT_NUM_PAGES              1057
#define IDC_ADD                         1058
#define IDC_DELETE                      1059
#define IDC_CHANGE                      1060
#define IDC_NAME                        1061
#define IDC_COMBO_PAGE_MODE             1062
#define IDC_COMBO_UNIT                  1063
#define IDC_COMBO_OPACITY               1064
#define IDC_CHECK_SPLASH                1065
#define ID_REGISTER_MIKTEX              32771
#define ID_VIEW_TRACE                   32772
#define ID_FILE_DOCUMENT_PROPERTIES     32773
#define ID_BACK                         32774
#define ID_CANCEL                       32775
#define ID_DARKER_TEXT                  32776
#define ID_DOCUMENT_DOWN                32777
#define ID_DOUBLE_PAGE                  32778
#define ID_END                          32779
#define ID_FILE_DVIPS                   32780
#define ID_FIRST_PAGE                   32781
#define ID_FORWARD                      32782
#define ID_FULLSCREEN                   32783
#define ID_GOTO_PAGE                    32784
#define ID_HELP_KEYBOARD                32785
#define ID_HOME                         32786
#define ID_INDICATOR_COMMAND_PREFIX     32787
#define ID_INDICATOR_PAGE_M_OF_N        32788
#define ID_INDICATOR_POINT              32789
#define ID_INDICATOR_SOURCE             32790
#define ID_LAST_PAGE                    32791
#define ID_LIGHT_TEXT                   32792
#define ID_LIGHTER_TEXT                 32793
#define ID_NEXT_PAGE                    32794
#define ID_PAGE_EDITOR                  32795
#define ID_PREV_PAGE                    32796
#define ID_SB_LINEDOWN                  32797
#define ID_SB_LINELEFT                  32798
#define ID_SB_LINERIGHT                 32799
#define ID_SB_LINEUP                    32800
#define ID_SB_PAGEDOWN                  32801
#define ID_SB_PAGELEFT                  32802
#define ID_SB_PAGERIGHT                 32803
#define ID_SB_PAGEUP                    32804
#define ID_SINGLE_PAGE                  32805
#define ID_TOOLS_ARROW                  32806
#define ID_TOOLS_HAND                   32807
#define ID_TOOLS_MAGNIFYING_GLASS       32808
#define ID_TOOLS_SOURCESPECIALS         32809
#define ID_VIEW_FULLSCREEN              32810
#define ID_VIEW_OPTIONS                 32811
#define ID_VIEW_REFRESH                 32812
#define ID_ZOOM_IN                      32813
#define ID_ZOOM_OUT                     32814
#define ID_CONTINUOUS_SINGLE            32815
#define ID_CONTINUOUS_DOUBLE            32816
#define ID_FILE_SAVEAS                  32817
#define ID_DOCUMENT_UP                  32818
#define ID_PAGEMODE_PK                  32820
#define ID_PAGEMODE_DVIPS               32821
#define ID_VIEW_CENTIMETERS             32822
#define ID_VIEW_INCHES                  32823
#define ID_VIEW_MILLIMETERS             32824
#define ID_VIEW_PICAS                   32825
#define ID_VIEW_POINTS                  32826
#define ID_INDICATOR_EFFECTIVE_PAGE_MODE 32827

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32828
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
