#!/bin/sh -e
. /usr/share/debconf/confmodule
db_get miktex/mklinks
if [ "$RET" = "force" ]; then
    initexmf --admin --disable-installer --update-fndb --force --mklinks
elif [ "$RET" = "yes" ]; then
    initexmf --admin --disable-installer --update-fndb --mklinks
else
    initexmf --admin --disable-installer --update-fndb
fi
db_get miktex/autoinstall
initexmf --admin --set-config-value=[MPM]AutoInstall="$RET"
