#!/bin/sh -e
. /usr/share/debconf/confmodule
initexmf --admin --disable-installer --update-fndb
db_get miktex/mklinks
if [ "$RET" = "force" ]; then
    initexmf --admin --disable-installer --force --mklinks
elif [ "$RET" = "yes" ]; then
    initexmf --admin --disable-installer --mklinks
fi
initexmf --admin --disable-installer --update-fndb
db_get miktex/autoinstall
initexmf --admin --set-config-value=[MPM]AutoInstall="$RET"
db_get miktex/othertexmf
#if [ "$RET" = "true" ]; then
#    initexmf --admin --register-other-roots
#fi
