/* Header for module utility, generated by p2c 1.21alpha-07.Dec.93 */
#ifndef UTILITY_H
#define UTILITY_H


#ifdef UTILITY_G
# define vextern
#else
# define vextern extern
#endif
/* DPL 2004-03-22 */

/* Utilities, mainly aids to parsing */


extern boolean equalsIgnoreCase(Char *s1, Char *s2);
extern boolean startsWithIgnoreCase(Char *s1, Char *s2);
extern boolean endsWith(Char *s1, Char *s2);
extern boolean startsWithBracedWord(Char *P);
extern Char *GetNextWord(Char *Result, Char *s, Char Delim, Char Term);
extern Char *NextWord(Char *Result, Char *s, Char Delim, Char Term);
extern short wordCount(Char *s);
extern Char *plural(Char *Result, short n);
extern short curtail(Char *s, Char c);
/* Remove last character if it equals c and return its position;
   otherwise return 0 */
extern Char *toString(Char *Result, short n);
extern void trim(Char *s);
extern short digit(Char c);
extern boolean match(Char *source, Char *pattern);
extern Char *translate(Char *Result, Char *source, Char *pattern,
		       Char *target);
extern void grep(Char *source, Char *pattern, Char *target);
/* See Implementation for what this currently does. */


#undef vextern

#endif /*UTILITY_H*/

/* End. */
