#line 2 "gabc/gabc-score-determination-l.c"

#line 4 "gabc/gabc-score-determination-l.c"

#define  YY_INT_ALIGNED long int

/* A lexical scanner generated by flex */

#define yy_create_buffer gabc_score_determination__create_buffer
#define yy_delete_buffer gabc_score_determination__delete_buffer
#define yy_flex_debug gabc_score_determination__flex_debug
#define yy_init_buffer gabc_score_determination__init_buffer
#define yy_flush_buffer gabc_score_determination__flush_buffer
#define yy_load_buffer_state gabc_score_determination__load_buffer_state
#define yy_switch_to_buffer gabc_score_determination__switch_to_buffer
#define yyin gabc_score_determination_in
#define yyleng gabc_score_determination_leng
#define yylex gabc_score_determination_lex
#define yylineno gabc_score_determination_lineno
#define yyout gabc_score_determination_out
#define yyrestart gabc_score_determination_restart
#define yytext gabc_score_determination_text
#define yywrap gabc_score_determination_wrap
#define yyalloc gabc_score_determination_alloc
#define yyrealloc gabc_score_determination_realloc
#define yyfree gabc_score_determination_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE gabc_score_determination_restart(gabc_score_determination_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t gabc_score_determination_leng;

extern FILE *gabc_score_determination_in, *gabc_score_determination_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gabc_score_determination_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up gabc_score_determination_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via gabc_score_determination_restart()), so that the user can continue scanning by
	 * just pointing gabc_score_determination_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when gabc_score_determination_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t gabc_score_determination_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow gabc_score_determination_wrap()'s to do buffer switches
 * instead of setting up a fresh gabc_score_determination_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void gabc_score_determination_restart (FILE *input_file  );
void gabc_score_determination__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE gabc_score_determination__create_buffer (FILE *file,int size  );
void gabc_score_determination__delete_buffer (YY_BUFFER_STATE b  );
void gabc_score_determination__flush_buffer (YY_BUFFER_STATE b  );
void gabc_score_determination_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void gabc_score_determination_pop_buffer_state (void );

static void gabc_score_determination_ensure_buffer_stack (void );
static void gabc_score_determination__load_buffer_state (void );
static void gabc_score_determination__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER gabc_score_determination__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE gabc_score_determination__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE gabc_score_determination__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE gabc_score_determination__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *gabc_score_determination_alloc (yy_size_t  );
void *gabc_score_determination_realloc (void *,yy_size_t  );
void gabc_score_determination_free (void *  );

#define yy_new_buffer gabc_score_determination__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        gabc_score_determination_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        gabc_score_determination_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define gabc_score_determination_wrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *gabc_score_determination_in = (FILE *) 0, *gabc_score_determination_out = (FILE *) 0;

typedef int yy_state_type;

extern int gabc_score_determination_lineno;

int gabc_score_determination_lineno = 1;

extern char *gabc_score_determination_text;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr gabc_score_determination_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up gabc_score_determination_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	gabc_score_determination_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int32_t yy_accept[296] =
    {   0,
        0,    0,    7,    7,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   72,   25,
       70,   25,   23,    6,   23,   23,   23,   23,   23,   23,
       23,   23,   23,    2,    2,    3,    3,    1,    7,    7,
       71,   27,   26,   49,   65,   28,   55,   63,   64,   56,
       57,   66,   68,   67,   27,   47,   48,   55,   71,   54,
       55,   51,   50,    5,    4,   55,    0,    0,   23,    6,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,    2,    1,    7,    7,    0,    7,    7,    0,    7,
        8,    0,   27,   26,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   66,   69,   27,   48,
       47,    0,   54,    0,   51,   50,    5,    4,    0,   24,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,    7,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   39,   37,   43,    0,   31,    0,    0,
        0,    0,    0,   52,   62,    0,    0,    0,   23,   23,
        0,   23,   23,   23,   14,   23,   10,   23,   23,   23,
       40,   38,   44,    0,   32,    0,    0,    0,    0,    0,
       60,    0,   41,   45,   33,   35,    0,   53,    0,   23,
       23,   23,    0,   23,   23,    0,    0,   23,   23,   23,

       61,    0,   42,   34,   36,   58,    0,   46,    0,   23,
       18,    9,   23,   23,   23,   23,   23,   23,   23,    0,
        0,    0,   29,   59,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   30,   23,   23,    0,   19,   23,
       23,   23,    0,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   17,   23,   23,   23,   23,   21,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   20,
       23,   23,   23,   23,   23,   23,   23,   13,   23,   15,
       23,   23,   12,   23,   23,   23,   23,   23,   11,   16,
       23,   23,   23,   22,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    6,    1,    7,    1,    1,    8,
        9,    1,    1,    1,   10,    1,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,   15,
        1,   16,    1,    1,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       18,    1,   19,    1,   17,    1,   20,   21,   22,   23,

       24,   25,   26,   27,   28,   17,   17,   29,   30,   31,
       32,   33,   17,   34,   35,   36,   37,   38,   17,   17,
       39,   17,   40,   41,   42,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   43,    1,    1,    1,
       44,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   45,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[46] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    3,    4,    5,
        1,    6,    1,    7,    8,    1,    6,    3,    3,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    9,
        4,    9,    1,    1,    1
    } ;

static yyconst flex_uint32_t yy_base[316] =
    {   0,
        0,   43,   48,   50,   86,  126,   39,   50,  166,  206,
      662,  661,   52,   54,   57,   62,  660,  659,  673,  678,
      678,  665,  661,  665,   61,   53,   58,   64,   59,   65,
       62,   66,   63,   80,   99,  678,  662,   63,  106,  108,
      110,    0,  113,  678,  678,  678,  238,  657,  678,  678,
      678,    0,  135,  678,  139,  148,    0,  656,  678,    0,
      655,    0,  128,    0,  139,  654,  152,    0,  654,  678,
      117,  125,  150,   60,  144,  152,  154,  157,  161,  169,
      170,  188,  150,  193,  201,  208,  649,  214,    0,  216,
      195,  199,    0,  229,  256,  633,  645,  644,  149,  643,

      629,  204,  621,  627,  639,  635,    0,  236,  235,    0,
      292,  618,    0,  614,    0,  232,    0,  247,  631,  252,
      640,  247,  217,  639,  178,  253,  242,  237,  260,  257,
      255,  254,  261,  634,  631,  630,  267,  629,  615,  621,
      606,  612,  604,  678,  678,  678,  623,  678,  617,  621,
      620,  619,  618,  678,  678,  600,  616,  602,  262,  275,
      600,  619,  289,  290,  618,  617,  616,  291,  292,  293,
      678,  678,  678,  609,  678,  603,  607,  606,  605,  604,
      678,  599,  678,  678,  678,  678,  602,  678,  581,  295,
      296,  109,  594,  299,  300,  291,  586,  298,  604,  601,

      678,  577,  678,  678,  678,  678,  572,  678,  569,  301,
      562,  555,  302,  153,  312,  313,  314,  315,  316,  536,
      523,  534,  678,  678,  319,  321,  539,  318,  323,  322,
      326,  444,  329,  330,  678,  334,  339,  415,  436,  340,
      342,  343,  413,  346,  345,  349,  350,  352,  353,  358,
      354,  359,  361,  362,  434,  363,  364,  365,  377,  433,
      380,  372,  375,  371,  382,  385,  388,  391,  386,  431,
      392,  394,  397,  403,  407,  406,  384,  426,  411,  424,
      412,  413,  219,  414,  415,  416,  419,  417,  213,  115,
      421,  423,  420,  113,  678,  455,  464,  473,  482,  491,

      500,  509,  514,  520,  529,  538,  547,  554,  563,  570,
      577,  586,  595,   61,  604
    } ;

static yyconst flex_int32_t yy_def[316] =
    {   0,
      295,    1,  296,  296,  297,  297,  298,  298,  299,  299,
      300,  300,  301,  301,  302,  302,  300,  300,  295,  295,
      295,  295,  303,  295,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  295,  295,  295,  295,  295,  304,  305,
      306,  307,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  308,  295,  295,  309,  295,  310,  295,  295,  311,
      295,  312,  295,  313,  295,  295,  295,  314,  303,  295,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  295,  295,  304,  305,  306,  305,  305,  315,  306,
      295,  295,  307,  295,  295,  295,  295,  295,  295,  295,

      295,  295,  295,  295,  295,  295,  308,  295,  309,  310,
      295,  295,  311,  295,  312,  295,  313,  295,  295,  295,
      314,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  315,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  303,  303,
      314,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  303,
      303,  314,  314,  303,  303,  314,  314,  303,  303,  303,

      295,  295,  295,  295,  295,  295,  295,  295,  295,  303,
      303,  314,  314,  303,  303,  314,  314,  314,  303,  314,
      314,  295,  295,  295,  303,  314,  303,  303,  314,  314,
      314,  303,  314,  314,  295,  303,  314,  314,  303,  314,
      314,  314,  314,  314,  314,  303,  314,  314,  314,  314,
      314,  314,  314,  314,  303,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,    0,  295,  295,  295,  295,  295,

      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295
    } ;

static yyconst flex_uint32_t yy_nxt[724] =
    {   0,
       20,   20,   21,   20,   20,   20,   22,   20,   20,   20,
       20,   23,   24,   20,   20,   20,   23,   20,   20,   25,
       23,   23,   26,   23,   23,   27,   23,   28,   29,   30,
       31,   32,   23,   23,   33,   23,   23,   23,   23,   20,
       20,   20,   20,   20,   20,   34,   35,   53,   36,   37,
       40,   40,   40,   40,   63,   63,   63,   63,   53,   65,
       65,   41,   68,   41,   65,   65,  121,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   73,   74,   76,   54,
      125,   78,   82,   82,   80,   38,   38,   38,   43,   43,
       54,   71,   44,   45,   75,   46,   77,   72,   81,   79,

       47,   82,   82,   48,   49,   83,   83,   83,   85,   85,
       88,   88,   91,   91,   94,   94,   94,   94,   68,   86,
      212,   89,   68,   92,   68,   50,   68,   51,   43,   43,
      116,  116,   44,   45,   68,   46,  108,  108,  108,  108,
       47,  118,  118,   48,   49,  110,  110,  122,  110,  111,
      111,  111,  111,   68,  120,  120,  110,  110,   67,   68,
      123,   68,   68,   68,  146,   50,   68,   51,   56,   56,
       68,  126,   57,   57,  124,   57,  128,  129,   68,   68,
       58,  227,  127,   57,   57,  147,  130,   68,  131,  133,
       82,   82,   83,   83,   83,   85,   85,   91,   91,  162,

      132,   91,   91,   88,   88,   59,   86,   59,   56,   56,
      295,  295,   57,   57,   89,   57,   88,   88,   85,   85,
       58,  295,   68,   57,   57,  150,   68,   89,   68,   86,
       94,   94,   94,   94,  116,  116,  151,  108,  108,  108,
      108,  110,  110,  160,  110,   59,   68,   59,   95,  118,
      118,   68,  110,  110,  120,  120,   68,   96,   97,   98,
      165,   99,   68,   68,   68,  100,   68,  164,  101,   68,
       68,   68,  102,  103,  104,  105,  135,  136,  159,  137,
      167,  166,  173,  138,   68,  170,  139,  169,  163,  168,
      140,  141,  142,  111,  111,  111,  111,  190,   68,   68,

       68,   68,   68,  174,   68,   68,  191,   68,   68,   68,
       68,   68,  198,  216,  210,  199,  194,  200,  214,  215,
      217,   68,   68,   68,   68,   68,  195,   68,   68,  211,
       68,   68,   68,  226,  219,   68,  225,  228,   68,   68,
      229,  239,  231,   68,  241,  230,  236,  240,   68,   68,
      232,   68,   68,  237,   68,   68,  242,  245,   68,   68,
      244,   68,   68,   68,  249,  246,  251,   68,   68,  250,
       68,   68,   68,   68,   68,  254,  258,  247,  253,  255,
       68,   68,  259,  256,   68,  263,   68,  257,  260,   68,
      264,   68,  261,   68,   68,   68,  271,   68,  266,  262,

       68,   68,  265,   68,  267,  269,   68,  268,  273,  270,
      272,  274,   68,  276,  275,   68,   68,  278,  277,  283,
       68,   68,   68,   68,   68,   68,   68,  279,   68,   68,
       68,  282,   68,   68,  288,   68,  280,  281,  290,  286,
       68,  287,   68,   68,  252,   68,  284,  285,  292,  248,
      294,  289,  291,  243,  293,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   60,   60,   60,   60,   60,   60,   60,   60,   60,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   69,   69,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   93,  238,  235,
       93,  234,   93,   93,  107,  107,  107,  233,  107,  107,
      107,  107,  107,  109,   68,  109,  109,  109,  109,  109,
      110,   68,  110,  110,  110,  110,  110,  113,  113,  113,
      113,  113,  113,  113,  224,  113,  115,  223,  115,  115,
      115,  115,  115,  115,  115,  117,  222,  117,  117,  117,

      117,  117,  117,  117,  134,  134,  134,  134,  134,  134,
      221,  134,  134,  220,  218,  213,  209,  208,  207,  206,
      205,  204,  203,  202,  201,   68,  197,  196,  193,  192,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  172,  171,   89,  161,   68,
      158,  157,  156,  155,  154,  153,  152,  149,  148,  145,
      144,  143,   89,   68,  119,  114,  112,  106,   67,   70,
       68,   67,  295,   66,   66,   61,   61,   19,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,

      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295
    } ;

static yyconst flex_int32_t yy_chk[724] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    2,    7,    2,    2,
        3,    3,    4,    4,   13,   13,   14,   14,    8,   15,
       15,    3,   26,    4,   16,   16,  314,   27,   29,   74,
       25,   31,   33,   28,   30,   32,   26,   27,   29,    7,
       74,   31,   34,   34,   33,    2,    2,    2,    5,    5,
        8,   25,    5,    5,   28,    5,   30,   25,   33,   32,

        5,   35,   35,    5,    5,   38,   38,   38,   39,   39,
       40,   40,   41,   41,   43,   43,   43,   43,  192,   39,
      192,   40,  294,   41,  290,    5,   71,    5,    6,    6,
       63,   63,    6,    6,   72,    6,   53,   53,   53,   53,
        6,   65,   65,    6,    6,   55,   55,   71,   55,   56,
       56,   56,   56,   75,   67,   67,   55,   55,   67,   73,
       72,   76,  214,   77,   99,    6,   78,    6,    9,    9,
       79,   75,    9,    9,   73,    9,   77,   78,   80,   81,
        9,  214,   76,    9,    9,   99,   78,  125,   79,   81,
       82,   82,   83,   83,   83,   84,   84,   91,   91,  125,

       80,   92,   92,   85,   85,    9,   84,    9,   10,   10,
       86,   86,   10,   10,   85,   10,   88,   88,   90,   90,
       10,   86,  289,   10,   10,  102,  123,   88,  283,   90,
       94,   94,   94,   94,  116,  116,  102,  108,  108,  108,
      108,  109,  109,  123,  109,   10,  128,   10,   47,  118,
      118,  127,  109,  109,  120,  120,  122,   47,   47,   47,
      128,   47,  126,  132,  131,   47,  130,  127,   47,  129,
      133,  159,   47,   47,   47,   47,   95,   95,  122,   95,
      130,  129,  137,   95,  160,  133,   95,  132,  126,  131,
       95,   95,   95,  111,  111,  111,  111,  159,  163,  164,

      168,  169,  170,  137,  190,  191,  160,  198,  194,  195,
      210,  213,  168,  196,  190,  169,  163,  170,  194,  195,
      196,  215,  216,  217,  218,  219,  164,  228,  225,  191,
      226,  230,  229,  213,  198,  231,  210,  215,  233,  234,
      216,  228,  218,  236,  230,  217,  225,  229,  237,  240,
      219,  241,  242,  226,  245,  244,  231,  234,  246,  247,
      233,  248,  249,  251,  240,  236,  242,  250,  252,  241,
      253,  254,  256,  257,  258,  245,  249,  237,  244,  246,
      264,  262,  250,  247,  263,  254,  259,  248,  251,  261,
      256,  265,  252,  277,  266,  269,  264,  267,  258,  253,

      268,  271,  257,  272,  259,  262,  273,  261,  266,  263,
      265,  267,  274,  269,  268,  276,  275,  272,  271,  277,
      279,  281,  282,  284,  285,  286,  288,  273,  287,  293,
      291,  276,  292,  280,  285,  278,  274,  275,  287,  282,
      270,  284,  260,  255,  243,  239,  279,  281,  291,  238,
      293,  286,  288,  232,  292,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  300,  300,  300,  300,  300,  300,  300,  300,  300,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  303,  303,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  307,  227,  222,
      307,  221,  307,  307,  308,  308,  308,  220,  308,  308,
      308,  308,  308,  309,  212,  309,  309,  309,  309,  309,
      310,  211,  310,  310,  310,  310,  310,  311,  311,  311,
      311,  311,  311,  311,  209,  311,  312,  207,  312,  312,
      312,  312,  312,  312,  312,  313,  202,  313,  313,  313,

      313,  313,  313,  313,  315,  315,  315,  315,  315,  315,
      200,  315,  315,  199,  197,  193,  189,  187,  182,  180,
      179,  178,  177,  176,  174,  167,  166,  165,  162,  161,
      158,  157,  156,  153,  152,  151,  150,  149,  147,  143,
      142,  141,  140,  139,  138,  136,  135,  134,  124,  121,
      119,  114,  112,  106,  105,  104,  103,  101,  100,   98,
       97,   96,   87,   69,   66,   61,   58,   48,   37,   24,
       23,   22,   19,   18,   17,   12,   11,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,

      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int gabc_score_determination__flex_debug;
int gabc_score_determination__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *gabc_score_determination_text;
#line 1 "gabc/gabc-score-determination.l"
#line 2 "gabc/gabc-score-determination.l"
/*
 * Gregorio is a program that translates gabc files to GregorioTeX
 * This file implements the score lexer.
 *
 * Gregorio score determination in gabc input.
 * Copyright (C) 2006-2016 The Gregorio Project (see CONTRIBUTORS.md)
 *
 * This file is part of Gregorio.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "struct.h"
#include "messages.h"
#include "bool.h"
#include "support.h"

#include "gabc.h"
#include "gabc-score-determination.h"
#include "gabc-score-determination-y.h"

static bool eof_found = false;

#define START_STYLE(STYLE) \
    if (*styles & SB_ ## STYLE) { \
        gregorio_messagef("gabc_score_determination_lex", VERBOSITY_ERROR, 0, \
                _("style already started: %s"), gabc_score_determination_text); \
    } else { \
        *styles ^= SB_ ## STYLE; \
        return STYLE ## _BEGIN; \
    }

#define END_STYLE(STYLE) \
    if (*styles & SB_ ## STYLE) { \
        *styles ^= SB_ ## STYLE; \
        return STYLE ## _END; \
    } else { \
        gregorio_messagef("gabc_score_determination_lex", VERBOSITY_ERROR, 0, \
                _("style not started: %s"), gabc_score_determination_text); \
    }

#define RETURN_CHARACTERS \
    gabc_score_determination_lval.text = \
            gregorio_strdup(gabc_score_determination_text); \
    return CHARACTERS

#define RETURN_SPACE \
    gabc_score_determination_lval.text = gregorio_strdup(" "); \
    return CHARACTERS

#define YY_NO_INPUT

#define YY_INPUT(buf,result,max_size) \
    if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) { \
        int c = '*'; \
        size_t n; \
        for (n = 0; n < max_size \
                && (c = getc(gabc_score_determination_in)) != EOF \
                && c != '\n'; ++n ) { \
            buf[n] = (char) c; \
        } \
        if (c == '\n') { \
            buf[n++] = (char) c; \
        } \
        if (c == EOF && ferror(gabc_score_determination_in)) { \
            YY_FATAL_ERROR("input in flex scanner failed"); \
        } \
        result = n; \
    } else { \
        errno=0; \
        while ((result = fread(buf, 1, max_size, gabc_score_determination_in)) \
                == 0 && ferror(gabc_score_determination_in)) { \
            if (errno != EINTR) { \
                YY_FATAL_ERROR("input in flex scanner failed"); \
                break; \
            } \
            errno = 0; \
            clearerr(gabc_score_determination_in); \
        } \
    } \
    gabc_digest(buf, result)

#define YY_USER_ACTION gabc_update_location(&gabc_score_determination_lloc, \
        gabc_score_determination_text, gabc_score_determination_leng);









/* The expression for attribute below is rather messy because we allow
for (a) single-line values, ending with a semicolon at end of line or a
double semicolon, (b) multi-line values, which end at a double
semicolon. */
#line 863 "gabc/gabc-score-determination-l.c"

#define INITIAL 0
#define attribute 1
#define score 2
#define notes 3
#define sp 4
#define verb 5
#define comments 6
#define inicomments 7
#define alt 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int gabc_score_determination_lex_destroy (void );

int gabc_score_determination_get_debug (void );

void gabc_score_determination_set_debug (int debug_flag  );

YY_EXTRA_TYPE gabc_score_determination_get_extra (void );

void gabc_score_determination_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *gabc_score_determination_get_in (void );

void gabc_score_determination_set_in  (FILE * _in_str  );

FILE *gabc_score_determination_get_out (void );

void gabc_score_determination_set_out  (FILE * _out_str  );

yy_size_t gabc_score_determination_get_leng (void );

char *gabc_score_determination_get_text (void );

int gabc_score_determination_get_lineno (void );

void gabc_score_determination_set_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int gabc_score_determination_wrap (void );
#else
extern int gabc_score_determination_wrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( gabc_score_determination_text, gabc_score_determination_leng, 1, gabc_score_determination_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( gabc_score_determination_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( gabc_score_determination_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, gabc_score_determination_in))==0 && ferror(gabc_score_determination_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(gabc_score_determination_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int gabc_score_determination_lex (void);

#define YY_DECL int gabc_score_determination_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after gabc_score_determination_text and gabc_score_determination_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( gabc_score_determination_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(gabc_score_determination_text[gabc_score_determination_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! gabc_score_determination_in )
			gabc_score_determination_in = stdin;

		if ( ! gabc_score_determination_out )
			gabc_score_determination_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			gabc_score_determination_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE );
		}

		gabc_score_determination__load_buffer_state( );
		}

	{
#line 134 "gabc/gabc-score-determination.l"

#line 1096 "gabc/gabc-score-determination-l.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of gabc_score_determination_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 296 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 678 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 135 "gabc/gabc-score-determination.l"
{
        /* BOM written by a lot of windows softwares when they write UTF-8 */
    }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 138 "gabc/gabc-score-determination.l"
{
        /* ignoring empty lines */
    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 141 "gabc/gabc-score-determination.l"
{
        BEGIN(inicomments);
    }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 144 "gabc/gabc-score-determination.l"
{
        BEGIN(INITIAL);
    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 147 "gabc/gabc-score-determination.l"
{
        /* ignored */
    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 150 "gabc/gabc-score-determination.l"
{
        BEGIN(attribute);
        return COLON;
    }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 154 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return ATTRIBUTE;
    }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 159 "gabc/gabc-score-determination.l"
{
         BEGIN(INITIAL);
         return SEMICOLON;
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 163 "gabc/gabc-score-determination.l"
{
         gabc_score_determination_lval.character = gabc_score_determination_text[5];
         return DEF_MACRO;
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 167 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
         return NAME;
    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 172 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return SCORE_COPYRIGHT;
    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 177 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return GABC_COPYRIGHT;
    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 182 "gabc/gabc-score-determination.l"
{
        /* DEPRECATED for removal in 5.0 */
        return INITIAL_STYLE;
    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 186 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return MODE;
    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 191 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return MODE_MODIFIER;
    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 196 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return MODE_DIFFERENTIA;
    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 201 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return ANNOTATION;
    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 206 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return AUTHOR;
    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 211 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return LANGUAGE;
    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 216 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return STAFF_LINES;
    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 221 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return NABC_LINES;
    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 226 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return ORISCUS_ORIENTATION;
    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 231 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return OTHER_HEADER;
    }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 236 "gabc/gabc-score-determination.l"
{
       BEGIN(score);
       return END_OF_DEFINITIONS;
    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 240 "gabc/gabc-score-determination.l"
{
        gregorio_messagef("det_score", VERBOSITY_ERROR, 0,
                _("unrecognized character: \"%c\" in definition part"),
                gabc_score_determination_text[0]);
    }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 245 "gabc/gabc-score-determination.l"
{
        RETURN_SPACE;
    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 248 "gabc/gabc-score-determination.l"
{
        RETURN_CHARACTERS;
    }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 251 "gabc/gabc-score-determination.l"
{
        return HYPHEN;
    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 254 "gabc/gabc-score-determination.l"
{
        return NLBA_B;
    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 257 "gabc/gabc-score-determination.l"
{
        return NLBA_E;
    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 260 "gabc/gabc-score-determination.l"
{
        START_STYLE(I);
    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 263 "gabc/gabc-score-determination.l"
{
        END_STYLE(I);
    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 266 "gabc/gabc-score-determination.l"
{
        START_STYLE(TT);
    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 269 "gabc/gabc-score-determination.l"
{
        END_STYLE(TT);
    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 272 "gabc/gabc-score-determination.l"
{
        START_STYLE(UL);
    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 275 "gabc/gabc-score-determination.l"
{
        END_STYLE(UL);
    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 278 "gabc/gabc-score-determination.l"
{
        START_STYLE(C);
    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 281 "gabc/gabc-score-determination.l"
{
        END_STYLE(C);
    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 284 "gabc/gabc-score-determination.l"
{
        START_STYLE(B);
    }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 287 "gabc/gabc-score-determination.l"
{
        END_STYLE(B);
    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 290 "gabc/gabc-score-determination.l"
{
        START_STYLE(SC);
    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 293 "gabc/gabc-score-determination.l"
{
        END_STYLE(SC);
    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 296 "gabc/gabc-score-determination.l"
{
        START_STYLE(ELISION);
    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 299 "gabc/gabc-score-determination.l"
{
        END_STYLE(ELISION);
    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 302 "gabc/gabc-score-determination.l"
{
        BEGIN(sp);
        return SP_BEGIN;
    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 306 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
        return SP_END;
    }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 310 "gabc/gabc-score-determination.l"
{
        RETURN_SPACE;
    }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 313 "gabc/gabc-score-determination.l"
{
        RETURN_CHARACTERS;
    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 316 "gabc/gabc-score-determination.l"
{
        BEGIN(comments);
    }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 319 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 322 "gabc/gabc-score-determination.l"
{
        /* ignored */
    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 325 "gabc/gabc-score-determination.l"
{
        BEGIN(verb);
        return VERB_BEGIN;
    }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 329 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
        return VERB_END;
    }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 333 "gabc/gabc-score-determination.l"
{
        RETURN_CHARACTERS;
    }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 336 "gabc/gabc-score-determination.l"
{
        RETURN_CHARACTERS;
    }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 339 "gabc/gabc-score-determination.l"
{
        return CENTER_BEGIN;
    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 342 "gabc/gabc-score-determination.l"
{
        return CENTER_END;
    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 345 "gabc/gabc-score-determination.l"
{
        BEGIN(alt);
        return ALT_BEGIN;
    }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 349 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
        return ALT_END;
    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 353 "gabc/gabc-score-determination.l"
{
        return EUOUAE_B;
    }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 356 "gabc/gabc-score-determination.l"
{
        return EUOUAE_E;
    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 359 "gabc/gabc-score-determination.l"
{
        return TRANSLATION_CENTER_END;
    }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 362 "gabc/gabc-score-determination.l"
{
        return TRANSLATION_BEGIN;
    }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 365 "gabc/gabc-score-determination.l"
{
        return TRANSLATION_END;
    }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 368 "gabc/gabc-score-determination.l"
{
        BEGIN(notes);
        return OPENING_BRACKET;
    }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 372 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return NOTES;
    }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 377 "gabc/gabc-score-determination.l"
{
        return NABC_CUT;
    }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 380 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
        return CLOSING_BRACKET;
    }
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 384 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
        return CLOSING_BRACKET_WITH_SPACE;
    }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(attribute):
case YY_STATE_EOF(score):
case YY_STATE_EOF(notes):
case YY_STATE_EOF(sp):
case YY_STATE_EOF(verb):
case YY_STATE_EOF(comments):
case YY_STATE_EOF(inicomments):
case YY_STATE_EOF(alt):
#line 388 "gabc/gabc-score-determination.l"
{
        if (!eof_found) {
            eof_found = true;
            return END_OF_FILE;
        } else {
            yyterminate();
        }
    }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 396 "gabc/gabc-score-determination.l"
{
        gregorio_messagef("gabc_score_determination_lex", VERBOSITY_ERROR, 0,
                _("unrecognized character: \"%c\""),
                gabc_score_determination_text[0]);
    }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 401 "gabc/gabc-score-determination.l"
ECHO;
	YY_BREAK
#line 1728 "gabc/gabc-score-determination-l.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed gabc_score_determination_in at a new source and called
			 * gabc_score_determination_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = gabc_score_determination_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( gabc_score_determination_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * gabc_score_determination_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of gabc_score_determination_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					gabc_score_determination_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			gabc_score_determination_restart(gabc_score_determination_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) gabc_score_determination_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 296 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 296 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 295);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					gabc_score_determination_restart(gabc_score_determination_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( gabc_score_determination_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve gabc_score_determination_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void gabc_score_determination_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        gabc_score_determination_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE );
	}

	gabc_score_determination__init_buffer(YY_CURRENT_BUFFER,input_file );
	gabc_score_determination__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void gabc_score_determination__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		gabc_score_determination_pop_buffer_state();
	 *		gabc_score_determination_push_buffer_state(new_buffer);
     */
	gabc_score_determination_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	gabc_score_determination__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (gabc_score_determination_wrap()) processing, but the only time this flag
	 * is looked at is after gabc_score_determination_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void gabc_score_determination__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	gabc_score_determination_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE gabc_score_determination__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) gabc_score_determination_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) gabc_score_determination_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__create_buffer()" );

	b->yy_is_our_buffer = 1;

	gabc_score_determination__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with gabc_score_determination__create_buffer()
 * 
 */
    void gabc_score_determination__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		gabc_score_determination_free((void *) b->yy_ch_buf  );

	gabc_score_determination_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a gabc_score_determination_restart() or at EOF.
 */
    static void gabc_score_determination__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	gabc_score_determination__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then gabc_score_determination__init_buffer was _probably_
     * called from gabc_score_determination_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void gabc_score_determination__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		gabc_score_determination__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void gabc_score_determination_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	gabc_score_determination_ensure_buffer_stack();

	/* This block is copied from gabc_score_determination__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from gabc_score_determination__switch_to_buffer. */
	gabc_score_determination__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void gabc_score_determination_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	gabc_score_determination__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		gabc_score_determination__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void gabc_score_determination_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
		(yy_buffer_stack) = (struct yy_buffer_state**)gabc_score_determination_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)gabc_score_determination_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE gabc_score_determination__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) gabc_score_determination_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	gabc_score_determination__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to gabc_score_determination_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       gabc_score_determination__scan_bytes() instead.
 */
YY_BUFFER_STATE gabc_score_determination__scan_string (yyconst char * yystr )
{
    
	return gabc_score_determination__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to gabc_score_determination_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE gabc_score_determination__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) gabc_score_determination_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = gabc_score_determination__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in gabc_score_determination__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gabc_score_determination_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		gabc_score_determination_text[gabc_score_determination_leng] = (yy_hold_char); \
		(yy_c_buf_p) = gabc_score_determination_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		gabc_score_determination_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int gabc_score_determination_get_lineno  (void)
{
        
    return gabc_score_determination_lineno;
}

/** Get the input stream.
 * 
 */
FILE *gabc_score_determination_get_in  (void)
{
        return gabc_score_determination_in;
}

/** Get the output stream.
 * 
 */
FILE *gabc_score_determination_get_out  (void)
{
        return gabc_score_determination_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t gabc_score_determination_get_leng  (void)
{
        return gabc_score_determination_leng;
}

/** Get the current token.
 * 
 */

char *gabc_score_determination_get_text  (void)
{
        return gabc_score_determination_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void gabc_score_determination_set_lineno (int  _line_number )
{
    
    gabc_score_determination_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see gabc_score_determination__switch_to_buffer
 */
void gabc_score_determination_set_in (FILE *  _in_str )
{
        gabc_score_determination_in = _in_str ;
}

void gabc_score_determination_set_out (FILE *  _out_str )
{
        gabc_score_determination_out = _out_str ;
}

int gabc_score_determination_get_debug  (void)
{
        return gabc_score_determination__flex_debug;
}

void gabc_score_determination_set_debug (int  _bdebug )
{
        gabc_score_determination__flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from gabc_score_determination_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    gabc_score_determination_in = stdin;
    gabc_score_determination_out = stdout;
#else
    gabc_score_determination_in = (FILE *) 0;
    gabc_score_determination_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * gabc_score_determination_lex_init()
     */
    return 0;
}

/* gabc_score_determination_lex_destroy is for both reentrant and non-reentrant scanners. */
int gabc_score_determination_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		gabc_score_determination__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		gabc_score_determination_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	gabc_score_determination_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        gabc_score_determination_free((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * gabc_score_determination_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *gabc_score_determination_alloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *gabc_score_determination_realloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void gabc_score_determination_free (void * ptr )
{
			free( (char *) ptr );	/* see gabc_score_determination_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 401 "gabc/gabc-score-determination.l"




