find_package(PkgConfig QUIET)

pkg_check_modules(_BOTAN110 REQUIRED botan-1.10)

find_path(BOTAN110_INCLUDE_DIR
  NAMES
    botan/botan.h
  HINTS
    ${_BOTAN110_INCLUDEDIR}
    ${_BOTAN110_INCLUDE_DIRS}
)

find_library(BOTAN110_LIBRARY
  NAMES
    botan-1.10
  HINTS
    ${_BOTAN110_LIBDIR}
    ${_BOTAN110_LIBRARY_DIRS}
)

find_package_handle_standard_args(BOTAN110 DEFAULT_MSG BOTAN110_LIBRARY BOTAN110_INCLUDE_DIR)

if(BOTAN110_FOUND)
  set(BOTAN110_INCLUDE_DIRS ${BOTAN110_INCLUDE_DIR})
  set(BOTAN110_LIBRARIES ${BOTAN110_LIBRARIES})
else()
  set(BOTAN110_INCLUDE_DIRS)
  set(BOTAN110_LIBRARIES)
endif()

mark_as_advanced(BOTAN110_LIBRARY BOTAN110_INCLUDE_DIR)
