# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '21 5 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        exempt-issue-labels: pinned
        stale-issue-message: 'This issue has been marked as stale due to inactivity.'
        stale-issue-label: 'no-issue-activity'
        close-issue-message: 'This issue has been automatically closed due to inactivity.'
        exempt-pr-labels: pinned
        stale-pr-message: 'This pull request has been marked as stale due to inactivity.'
        stale-pr-label: 'no-pr-activity'
        close-pr-message: 'This pull request has been automatically closed due to inactivity.'
